/* Generated By:JavaCC: Do not edit this line. CQELSParserConstants.java */
/*
 * (c) Copyright 2004, 2005, 2006, 2007, 2008, 2009 Hewlett-Packard Development Company, LP
 * (c) Copyright 2010 Talis Systems Ltd
 * All rights reserved.
 */
package org.deri.cqels.lang.cqels;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CQELSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WS = 7;
  /** RegularExpression Id. */
  int WSC = 8;
  /** RegularExpression Id. */
  int IRIref = 9;
  /** RegularExpression Id. */
  int PNAME_NS = 10;
  /** RegularExpression Id. */
  int PNAME_LN = 11;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 12;
  /** RegularExpression Id. */
  int VAR1 = 13;
  /** RegularExpression Id. */
  int VAR2 = 14;
  /** RegularExpression Id. */
  int LANGTAG = 15;
  /** RegularExpression Id. */
  int A2Z = 16;
  /** RegularExpression Id. */
  int A2ZN = 17;
  /** RegularExpression Id. */
  int KW_A = 18;
  /** RegularExpression Id. */
  int BASE = 19;
  /** RegularExpression Id. */
  int PREFIX = 20;
  /** RegularExpression Id. */
  int SELECT = 21;
  /** RegularExpression Id. */
  int DISTINCT = 22;
  /** RegularExpression Id. */
  int REDUCED = 23;
  /** RegularExpression Id. */
  int DESCRIBE = 24;
  /** RegularExpression Id. */
  int CONSTRUCT = 25;
  /** RegularExpression Id. */
  int ASK = 26;
  /** RegularExpression Id. */
  int LIMIT = 27;
  /** RegularExpression Id. */
  int OFFSET = 28;
  /** RegularExpression Id. */
  int ORDER = 29;
  /** RegularExpression Id. */
  int BY = 30;
  /** RegularExpression Id. */
  int BINDINGS = 31;
  /** RegularExpression Id. */
  int UNDEF = 32;
  /** RegularExpression Id. */
  int ASC = 33;
  /** RegularExpression Id. */
  int DESC = 34;
  /** RegularExpression Id. */
  int NAMED = 35;
  /** RegularExpression Id. */
  int FROM = 36;
  /** RegularExpression Id. */
  int WHERE = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int GRAPH = 39;
  /** RegularExpression Id. */
  int STREAM = 40;
  /** RegularExpression Id. */
  int RANGE = 41;
  /** RegularExpression Id. */
  int TRIPLES = 42;
  /** RegularExpression Id. */
  int SLIDE = 43;
  /** RegularExpression Id. */
  int OPTIONAL = 44;
  /** RegularExpression Id. */
  int UNION = 45;
  /** RegularExpression Id. */
  int MINUS_P = 46;
  /** RegularExpression Id. */
  int BIND = 47;
  /** RegularExpression Id. */
  int SERVICE = 48;
  /** RegularExpression Id. */
  int LET = 49;
  /** RegularExpression Id. */
  int FETCH = 50;
  /** RegularExpression Id. */
  int EXISTS = 51;
  /** RegularExpression Id. */
  int NOT = 52;
  /** RegularExpression Id. */
  int AS = 53;
  /** RegularExpression Id. */
  int GROUP = 54;
  /** RegularExpression Id. */
  int HAVING = 55;
  /** RegularExpression Id. */
  int SEPARATOR = 56;
  /** RegularExpression Id. */
  int AGG = 57;
  /** RegularExpression Id. */
  int COUNT = 58;
  /** RegularExpression Id. */
  int MIN = 59;
  /** RegularExpression Id. */
  int MAX = 60;
  /** RegularExpression Id. */
  int SUM = 61;
  /** RegularExpression Id. */
  int AVG = 62;
  /** RegularExpression Id. */
  int STDDEV = 63;
  /** RegularExpression Id. */
  int SAMPLE = 64;
  /** RegularExpression Id. */
  int GROUP_CONCAT = 65;
  /** RegularExpression Id. */
  int FILTER = 66;
  /** RegularExpression Id. */
  int BOUND = 67;
  /** RegularExpression Id. */
  int COALESCE = 68;
  /** RegularExpression Id. */
  int IN = 69;
  /** RegularExpression Id. */
  int IF = 70;
  /** RegularExpression Id. */
  int BNODE = 71;
  /** RegularExpression Id. */
  int IRI = 72;
  /** RegularExpression Id. */
  int URI = 73;
  /** RegularExpression Id. */
  int CAST = 74;
  /** RegularExpression Id. */
  int CALL = 75;
  /** RegularExpression Id. */
  int STR = 76;
  /** RegularExpression Id. */
  int STRLANG = 77;
  /** RegularExpression Id. */
  int STRDT = 78;
  /** RegularExpression Id. */
  int DTYPE = 79;
  /** RegularExpression Id. */
  int LANG = 80;
  /** RegularExpression Id. */
  int LANGMATCHES = 81;
  /** RegularExpression Id. */
  int IS_URI = 82;
  /** RegularExpression Id. */
  int IS_IRI = 83;
  /** RegularExpression Id. */
  int IS_BLANK = 84;
  /** RegularExpression Id. */
  int IS_LITERAL = 85;
  /** RegularExpression Id. */
  int IS_NUMERIC = 86;
  /** RegularExpression Id. */
  int REGEX = 87;
  /** RegularExpression Id. */
  int SAME_TERM = 88;
  /** RegularExpression Id. */
  int RAND = 89;
  /** RegularExpression Id. */
  int ABS = 90;
  /** RegularExpression Id. */
  int CEIL = 91;
  /** RegularExpression Id. */
  int FLOOR = 92;
  /** RegularExpression Id. */
  int ROUND = 93;
  /** RegularExpression Id. */
  int CONCAT = 94;
  /** RegularExpression Id. */
  int SUBSTR = 95;
  /** RegularExpression Id. */
  int STRLEN = 96;
  /** RegularExpression Id. */
  int UCASE = 97;
  /** RegularExpression Id. */
  int LCASE = 98;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 99;
  /** RegularExpression Id. */
  int CONTAINS = 100;
  /** RegularExpression Id. */
  int STRSTARTS = 101;
  /** RegularExpression Id. */
  int STRENDS = 102;
  /** RegularExpression Id. */
  int YEAR = 103;
  /** RegularExpression Id. */
  int MONTH = 104;
  /** RegularExpression Id. */
  int DAY = 105;
  /** RegularExpression Id. */
  int HOURS = 106;
  /** RegularExpression Id. */
  int MINUTES = 107;
  /** RegularExpression Id. */
  int SECONDS = 108;
  /** RegularExpression Id. */
  int TIMEZONE = 109;
  /** RegularExpression Id. */
  int TZ = 110;
  /** RegularExpression Id. */
  int NOW = 111;
  /** RegularExpression Id. */
  int VERSION = 112;
  /** RegularExpression Id. */
  int MD5 = 113;
  /** RegularExpression Id. */
  int SHA1 = 114;
  /** RegularExpression Id. */
  int SHA224 = 115;
  /** RegularExpression Id. */
  int SHA256 = 116;
  /** RegularExpression Id. */
  int SHA384 = 117;
  /** RegularExpression Id. */
  int SHA512 = 118;
  /** RegularExpression Id. */
  int TRUE = 119;
  /** RegularExpression Id. */
  int FALSE = 120;
  /** RegularExpression Id. */
  int DATA = 121;
  /** RegularExpression Id. */
  int INSERT = 122;
  /** RegularExpression Id. */
  int DELETE = 123;
  /** RegularExpression Id. */
  int INSERT_DATA = 124;
  /** RegularExpression Id. */
  int DELETE_DATA = 125;
  /** RegularExpression Id. */
  int DELETE_WHERE = 126;
  /** RegularExpression Id. */
  int MODIFY = 127;
  /** RegularExpression Id. */
  int LOAD = 128;
  /** RegularExpression Id. */
  int CLEAR = 129;
  /** RegularExpression Id. */
  int CREATE = 130;
  /** RegularExpression Id. */
  int ADD = 131;
  /** RegularExpression Id. */
  int MOVE = 132;
  /** RegularExpression Id. */
  int COPY = 133;
  /** RegularExpression Id. */
  int META = 134;
  /** RegularExpression Id. */
  int SILENT = 135;
  /** RegularExpression Id. */
  int DROP = 136;
  /** RegularExpression Id. */
  int INTO = 137;
  /** RegularExpression Id. */
  int TO = 138;
  /** RegularExpression Id. */
  int DFT = 139;
  /** RegularExpression Id. */
  int ALL = 140;
  /** RegularExpression Id. */
  int WITH = 141;
  /** RegularExpression Id. */
  int USING = 142;
  /** RegularExpression Id. */
  int DIGITS = 143;
  /** RegularExpression Id. */
  int INTEGER = 144;
  /** RegularExpression Id. */
  int DURATION = 145;
  /** RegularExpression Id. */
  int DECIMAL = 146;
  /** RegularExpression Id. */
  int DOUBLE = 147;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 148;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 149;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 150;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 151;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 152;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 153;
  /** RegularExpression Id. */
  int EXPONENT = 154;
  /** RegularExpression Id. */
  int QUOTE_3D = 155;
  /** RegularExpression Id. */
  int QUOTE_3S = 156;
  /** RegularExpression Id. */
  int ECHAR = 157;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 158;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 159;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 160;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 161;
  /** RegularExpression Id. */
  int LPAREN = 162;
  /** RegularExpression Id. */
  int RPAREN = 163;
  /** RegularExpression Id. */
  int NIL = 164;
  /** RegularExpression Id. */
  int LBRACE = 165;
  /** RegularExpression Id. */
  int RBRACE = 166;
  /** RegularExpression Id. */
  int LBRACKET = 167;
  /** RegularExpression Id. */
  int RBRACKET = 168;
  /** RegularExpression Id. */
  int ANON = 169;
  /** RegularExpression Id. */
  int SEMICOLON = 170;
  /** RegularExpression Id. */
  int COMMA = 171;
  /** RegularExpression Id. */
  int DOT = 172;
  /** RegularExpression Id. */
  int EQ = 173;
  /** RegularExpression Id. */
  int NE = 174;
  /** RegularExpression Id. */
  int GT = 175;
  /** RegularExpression Id. */
  int LT = 176;
  /** RegularExpression Id. */
  int LE = 177;
  /** RegularExpression Id. */
  int GE = 178;
  /** RegularExpression Id. */
  int BANG = 179;
  /** RegularExpression Id. */
  int TILDE = 180;
  /** RegularExpression Id. */
  int COLON = 181;
  /** RegularExpression Id. */
  int SC_OR = 182;
  /** RegularExpression Id. */
  int SC_AND = 183;
  /** RegularExpression Id. */
  int PLUS = 184;
  /** RegularExpression Id. */
  int MINUS = 185;
  /** RegularExpression Id. */
  int STAR = 186;
  /** RegularExpression Id. */
  int SLASH = 187;
  /** RegularExpression Id. */
  int DATATYPE = 188;
  /** RegularExpression Id. */
  int AT = 189;
  /** RegularExpression Id. */
  int ASSIGN = 190;
  /** RegularExpression Id. */
  int VBAR = 191;
  /** RegularExpression Id. */
  int CARAT = 192;
  /** RegularExpression Id. */
  int FPATH = 193;
  /** RegularExpression Id. */
  int RPATH = 194;
  /** RegularExpression Id. */
  int QMARK = 195;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 196;
  /** RegularExpression Id. */
  int PN_CHARS_U = 197;
  /** RegularExpression Id. */
  int PN_CHARS = 198;
  /** RegularExpression Id. */
  int PN_PREFIX = 199;
  /** RegularExpression Id. */
  int PN_LOCAL = 200;
  /** RegularExpression Id. */
  int VARNAME = 201;
  /** RegularExpression Id. */
  int UNKNOWN = 202;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<WS>",
    "<WSC>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"bindings\"",
    "\"undef\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"stream\"",
    "\"range\"",
    "\"triples\"",
    "\"slide\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"bind\"",
    "\"service\"",
    "\"let\"",
    "\"fetch\"",
    "\"exists\"",
    "\"not\"",
    "\"as\"",
    "\"group\"",
    "\"having\"",
    "\"separator\"",
    "\"agg\"",
    "\"count\"",
    "\"min\"",
    "\"max\"",
    "\"sum\"",
    "\"avg\"",
    "\"stdev\"",
    "\"sample\"",
    "\"group_concat\"",
    "\"filter\"",
    "\"bound\"",
    "\"coalesce\"",
    "\"in\"",
    "\"if\"",
    "\"bnode\"",
    "\"iri\"",
    "\"uri\"",
    "\"cast\"",
    "\"call\"",
    "\"str\"",
    "\"strlang\"",
    "\"strdt\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"RAND\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"CONCAT\"",
    "\"SUBSTR\"",
    "\"STRLEN\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"strSTARTS\"",
    "\"strENDS\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"NOW\"",
    "\"VERSION\"",
    "\"MD5\"",
    "\"SHA1\"",
    "\"SHA224\"",
    "\"SHA256\"",
    "\"SHA384\"",
    "\"SHA512\"",
    "\"true\"",
    "\"false\"",
    "\"data\"",
    "\"insert\"",
    "\"delete\"",
    "<INSERT_DATA>",
    "<DELETE_DATA>",
    "<DELETE_WHERE>",
    "\"modify\"",
    "\"load\"",
    "\"clear\"",
    "\"create\"",
    "\"add\"",
    "\"move\"",
    "\"copy\"",
    "\"meta\"",
    "\"silent\"",
    "\"drop\"",
    "\"into\"",
    "\"to\"",
    "\"default\"",
    "\"all\"",
    "\"with\"",
    "\"using\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DURATION>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "\":=\"",
    "\"|\"",
    "\"^\"",
    "\"->\"",
    "\"<-\"",
    "\"?\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<UNKNOWN>",
  };

}
